/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shaer
 */
public class FrmAgents extends javax.swing.JFrame {

    /**
     * Creates new form FrmAgents
     */
    public FrmAgents() {
        initComponents();
        cmbCompany.addItem("Hikma");
        cmbCompany.addItem("Pfizer");
        cmbCompany.addItem("Dar Al Dawa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idcompany = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PHONE = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnclear = new javax.swing.JButton();
        txtAge = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        rdmale = new javax.swing.JRadioButton();
        rdfemale = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAgents = new javax.swing.JTable();
        cmbCompany = new javax.swing.JComboBox<>();
        btngo = new javax.swing.JButton();
        lblmedicines = new javax.swing.JLabel();
        lblcompany = new javax.swing.JLabel();
        lblSelling = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Information Agents");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MANAGE AGENTS");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ID");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("NAME");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("AGE");

        idcompany.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        idcompany.setForeground(new java.awt.Color(0, 102, 102));
        idcompany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idcompany.setText("Company ");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("GENDER");

        PHONE.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        PHONE.setForeground(new java.awt.Color(0, 102, 102));
        PHONE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PHONE.setText("PHONE");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(153, 153, 153));
        btnAdd.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 102, 102));
        btnAdd.setText("ADD");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setOpaque(false);
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(153, 153, 153));
        btnDelete.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 102, 102));
        btnDelete.setText("DELETE");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setOpaque(false);
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(153, 153, 153));
        btnUpdate.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 102, 102));
        btnUpdate.setText("UPDATE");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.setOpaque(false);
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("AGENTS LIST");

        btnclear.setBackground(new java.awt.Color(153, 153, 153));
        btnclear.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        btnclear.setForeground(new java.awt.Color(0, 102, 102));
        btnclear.setText("CLEAR");
        btnclear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclear.setOpaque(false);
        btnclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnclearMouseClicked(evt);
            }
        });
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        GenderGroup.add(rdmale);
        rdmale.setSelected(true);
        rdmale.setText("Male");

        GenderGroup.add(rdfemale);
        rdfemale.setText("Female");

        tableAgents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "AGE", "PHONE", "GENDER", "COMPANY"
            }
        ));
        tableAgents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAgentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAgents);

        btngo.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        btngo.setForeground(new java.awt.Color(0, 102, 102));
        btngo.setText("Next");
        btngo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idcompany)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCompany, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PHONE)
                        .addGap(32, 32, 32)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdmale)
                        .addGap(18, 18, 18)
                        .addComponent(rdfemale)))
                .addGap(71, 71, 71))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnAdd)
                        .addGap(35, 35, 35)
                        .addComponent(btnUpdate)
                        .addGap(200, 200, 200)
                        .addComponent(btnclear))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btngo)
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PHONE, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdmale)
                            .addComponent(rdfemale))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(idcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btngo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        lblmedicines.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        lblmedicines.setForeground(new java.awt.Color(255, 255, 255));
        lblmedicines.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmedicines.setText("MEDICINES");
        lblmedicines.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblmedicinesMouseClicked(evt);
            }
        });

        lblcompany.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        lblcompany.setForeground(new java.awt.Color(255, 255, 255));
        lblcompany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcompany.setText("COMPANY");
        lblcompany.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcompanyMouseClicked(evt);
            }
        });

        lblSelling.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        lblSelling.setForeground(new java.awt.Color(255, 255, 255));
        lblSelling.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelling.setText("SELLING");
        lblSelling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSellingMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblmedicines, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSelling, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(lblcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblmedicines, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblSelling, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
////        try {
////            con=DriverManager.getConnection("jdbc:derby://localhost:1527/Pharmadb","aya","123");
////            PreparedStatement add=con.prepareStatement("insert into AAGENTTBL values( ?,?,?,?,?,?)");
////            add.setInt(1,Integer.valueOf(Aid.getText()));
////            add.setString(2,Aname.getText());
////            add.setInt(3,Integer.valueOf(Aage.getText()));
////            add.setString(4,Aphone.getText());
////            add.setString(5,Apass.getText());
////
////            add.setString(6,GenderCb.getSelectedItem().toString());
////            int row=add.executeUpdate();
////            JOptionPane.showMessageDialog(this,"Agent Successfully Added");
////            con.close();
////            selectMed();
////        } catch (SQLException e) {
////            JOptionPane.showMessageDialog(this, e.getMessage());
////            e.printStackTrace();
////        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      if (idValidation(txtID)&&  nameValidation(txtName)&&phoneNumValidation(txtPhone)
            &&ageNumValidation(txtAge) ) {
          String id = txtID.getText().trim();  
          String name = txtName.getText().trim();
          String phoneNum = txtPhone.getText().trim(); 
          String ageNum = txtAge.getText().trim();  

    String gender="";

    if(rdmale.isSelected())
        gender="Male";

    if(rdfemale.isSelected())
        gender="Female";

    DefaultTableModel model =
    (DefaultTableModel)tableAgents.getModel();

    model.addRow(new Object[]{
        txtID.getText(),
        txtName.getText(),
        txtAge.getText(),
        txtPhone.getText(),
        gender,
        cmbCompany.getSelectedItem().toString()
    });
      }
    }//GEN-LAST:event_btnAddActionPerformed
public boolean idValidation(JTextField txt) {
        try {
            String idText = txt.getText().trim();
            int id = Integer.parseInt(idText);
            if (idText.length() >= 4) {
                JOptionPane.showMessageDialog(this, "Id Length must be Less than 4");
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Id must be a number");
            txt.requestFocus();
            txt.setBorder(BorderFactory.createLineBorder(Color.red));
            return false;
        }
        txt.setBorder(BorderFactory.createLineBorder(Color.gray));
        return true;
    }
    public boolean nameValidation(JTextField txt){
        String text = txt.getText().trim();
        if (text.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name Field Required");
            txt.requestFocus();
            txt.setBorder(BorderFactory.createLineBorder(Color.red));
           return false; 
        }
          txt.setBorder(BorderFactory.createLineBorder(Color.gray));
        return true;
    }
     public boolean ageNumValidation(JTextField txt) {
        try {
            String phoneNumText = txt.getText().trim();
            int phoneNumber = Integer.parseInt(phoneNumText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Must Be A Number");
            txt.requestFocus();
            txt.setBorder(BorderFactory.createLineBorder(Color.red));
            return false;
        }
        txt.setBorder(BorderFactory.createLineBorder(Color.gray));
        return true;
    }
    
    
     public boolean phoneNumValidation(JTextField txt) {
        try {
            String phoneNumText = txt.getText().trim();
            int phoneNumber = Integer.parseInt(phoneNumText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Must Be A Number");
            txt.requestFocus();
            txt.setBorder(BorderFactory.createLineBorder(Color.red));
            return false;
        }
        txt.setBorder(BorderFactory.createLineBorder(Color.gray));
        return true;
    }
    
    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
////        if(Aid.getText().isEmpty()){
////            JOptionPane.showMessageDialog(this,"Enter The Agent To Be Deleted");
////        }
////        else
////        try {
////            con=DriverManager.getConnection("jdbc:derby://localhost:1527/Pharmadb","aya","123");
////            String Id=Aid.getText();
////            String Query="Delete from AYA.AAGENTTBL where AID="+Id;
////            Statement Add=con.createStatement();
////            Add.executeUpdate(Query);
////            selectMed();
////            JOptionPane.showMessageDialog(this, "Medicine  Delete Successfully " );
////        } catch (SQLException e) {
////            e.printStackTrace();
////        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
   

    DefaultTableModel model =
    (DefaultTableModel)tableAgents.getModel();

    int row = tableAgents.getSelectedRow();

    if(row != -1)
    {
        model.removeRow(row);
    }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
////        // التحقق من أن جميع الحقول ممتلئة
////        if(Aid.getText().isEmpty() || Aname.getText().isEmpty() || Aage.getText().isEmpty() || Aphone.getText().isEmpty() || Apass.getText().isEmpty()){
////            JOptionPane.showMessageDialog(this, "Missing Information");
////        }
////        else {
////            try {
////                // 1. فتح الاتصال بقاعدة البيانات
////                con = DriverManager.getConnection("jdbc:derby://localhost:1527/Pharmadb", "aya", "123");
////
////                // 2. جملة SQL الصحيحة (تحتوي على 6 علامات استفهام)
////                String UpdateQuery = "UPDATE AYA.AAGENTTBL SET ANAME=?, AAGE=?, APHONE=?, APASS=?, AGENDER=? WHERE AID=?";
////
////                PreparedStatement pstmt = con.prepareStatement(UpdateQuery);
////
////                // 3. ربط القيم بالترتيب الصحيح والمطابق لجملة SQL
////                pstmt.setString(1, Aname.getText());   // الاسم (ANAME)
////                pstmt.setString(2, Aage.getText());    // العمر (AAGE)
////                pstmt.setString(3, Aphone.getText());  // الهاتف (APHONE)
////                pstmt.setString(4, Apass.getText());   // كلمة السر (APASS)
////                pstmt.setString(5, GenderCb.getSelectedItem().toString()); // النوع (AGENDER)
////
////                // القيمة السادسة (AID) التي تأتي بعد كلمة WHERE لتحديد السطر المطلوب تعديله
////                pstmt.setInt(6, Integer.parseInt(Aid.getText()));
////
////                // 4. تنفيذ التعديل
////                int rowsAffected = pstmt.executeUpdate();
////
////                if (rowsAffected > 0) {
////                    JOptionPane.showMessageDialog(this, "Agent Updated Successfully");
////                    // 5. استدعاء دالة التحديث (تأكد من كتابة اسمها كما هي معرفة عندك)
////                    selectMed();
////                } else {
////                    JOptionPane.showMessageDialog(this, "Agent ID not found!");
////                }
////
////                // 6. إغلاق الاتصال
////                con.close();
////
////            } catch (SQLException e) {
////                // في حال حدوث خطأ في قاعدة البيانات
////                e.printStackTrace();
////                JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
////            } catch (NumberFormatException e) {
////                // في حال تم إدخال نص في خانة الـ ID (الذي يجب أن يكون رقماً)
////                JOptionPane.showMessageDialog(this, "ID must be a number!");
////            } catch (Exception e) {
////                // أي أخطاء أخرى
////                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
////            }
////        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
     
    String gender="";

    if(rdmale.isSelected())
        gender="Male";

    if(rdfemale.isSelected())
        gender="Female";

    DefaultTableModel model =
    (DefaultTableModel)tableAgents.getModel();

    int row = tableAgents.getSelectedRow();

    if(row != -1)
    {
        model.setValueAt(txtID.getText(), row, 0);
        model.setValueAt(txtName.getText(), row, 1);
        model.setValueAt(txtAge.getText(), row, 2);
        model.setValueAt(txtPhone.getText(), row, 3);
        model.setValueAt(gender, row, 4);
        model.setValueAt(
            cmbCompany.getSelectedItem().toString(),
            row,
            5
        );
    }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnclearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearMouseClicked
//////        Aid.setText("");
//////        Aname.setText("");
//////        Aage.setText("");
//////        Aphone.setText("");
//////        Apass.setText("");
    }//GEN-LAST:event_btnclearMouseClicked

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
    
    txtID.setText("");
    txtName.setText("");
    txtAge.setText("");
    txtPhone.setText("");

    rdmale.setSelected(false);
    rdfemale.setSelected(false);

    cmbCompany.setSelectedIndex(0);

    }//GEN-LAST:event_btnclearActionPerformed

    private void lblmedicinesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmedicinesMouseClicked
//        new MEDICINE().setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_lblmedicinesMouseClicked

    private void lblcompanyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcompanyMouseClicked
//        new COMPANY().setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_lblcompanyMouseClicked

    private void lblSellingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSellingMouseClicked
//        new Seling().setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_lblSellingMouseClicked

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void tableAgentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAgentsMouseClicked
       
    
    int row = tableAgents.getSelectedRow();

    txtID.setText(tableAgents.getValueAt(row,0).toString());
    txtName.setText(tableAgents.getValueAt(row,1).toString());
    txtAge.setText(tableAgents.getValueAt(row,2).toString());
    txtPhone.setText(tableAgents.getValueAt(row,3).toString());

    String gender =
    tableAgents.getValueAt(row,4).toString();

    if(gender.equals("Male"))
        rdmale.setSelected(true);
    else
        rdfemale.setSelected(true);

    cmbCompany.setSelectedItem(
        tableAgents.getValueAt(row,5).toString()
    );

    }//GEN-LAST:event_tableAgentsMouseClicked

    private void btngoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngoActionPerformed
        frmMediine Agents=new frmMediine();
        Agents.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btngoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAgents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GenderGroup;
    private javax.swing.JLabel PHONE;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btngo;
    private javax.swing.JComboBox<String> cmbCompany;
    private javax.swing.JLabel idcompany;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSelling;
    private javax.swing.JLabel lblcompany;
    private javax.swing.JLabel lblmedicines;
    private javax.swing.JRadioButton rdfemale;
    private javax.swing.JRadioButton rdmale;
    private javax.swing.JTable tableAgents;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
