/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shaer
 */
public class frmMediine extends javax.swing.JFrame {

    /**
     * Creates new form frmMediine
     */
    public frmMediine() {
        initComponents();
        cmbCompany.addItem("Hikma");
        cmbCompany.addItem("Pfizer");
        cmbCompany.addItem("Dar Al Dawa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlInfo = new javax.swing.JPanel();
        lblcompany = new javax.swing.JLabel();
        lblMedicines = new javax.swing.JLabel();
        lblSelling = new javax.swing.JLabel();
        txtFabdate = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        lblmednane = new javax.swing.JLabel();
        lblBRICE = new javax.swing.JLabel();
        lblQuantiy = new javax.swing.JLabel();
        txtMedName = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        lblFabdate = new javax.swing.JLabel();
        lblEXPDATE = new javax.swing.JLabel();
        lblCOMPANY = new javax.swing.JLabel();
        txtFabDate = new javax.swing.JTextField();
        txtExpDate = new javax.swing.JTextField();
        cmbCompany = new javax.swing.JComboBox<>();
        AddBin = new javax.swing.JButton();
        UpdateBin = new javax.swing.JButton();
        DeleteBin = new javax.swing.JButton();
        ClearBin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMedicine = new javax.swing.JTable();
        jLabel51 = new javax.swing.JLabel();
        btngo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("THE MANAGE MEDICINE");
        setResizable(false);

        PnlInfo.setBackground(new java.awt.Color(0, 102, 102));

        lblcompany.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        lblcompany.setForeground(new java.awt.Color(255, 255, 255));
        lblcompany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcompany.setText("COMPANY");
        lblcompany.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcompanyMouseClicked(evt);
            }
        });

        lblMedicines.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        lblMedicines.setForeground(new java.awt.Color(255, 255, 255));
        lblMedicines.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedicines.setText("MEDICINES");
        lblMedicines.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMedicinesMouseClicked(evt);
            }
        });

        lblSelling.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        lblSelling.setForeground(new java.awt.Color(255, 255, 255));
        lblSelling.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelling.setText("SELLING");
        lblSelling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSellingMouseClicked(evt);
            }
        });

        txtFabdate.setBackground(new java.awt.Color(255, 255, 255));

        jLabel45.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(51, 51, 51));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("MANAGE MEDICINES");

        lblid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblid.setForeground(new java.awt.Color(0, 102, 102));
        lblid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblid.setText("ID");

        lblmednane.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblmednane.setForeground(new java.awt.Color(0, 102, 102));
        lblmednane.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmednane.setText("MEDNAME");

        lblBRICE.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblBRICE.setForeground(new java.awt.Color(0, 102, 102));
        lblBRICE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBRICE.setText("PRICE");

        lblQuantiy.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblQuantiy.setForeground(new java.awt.Color(0, 102, 102));
        lblQuantiy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantiy.setText("QUANTITY");

        txtMedName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedNameActionPerformed(evt);
            }
        });

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        lblFabdate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblFabdate.setForeground(new java.awt.Color(0, 102, 102));
        lblFabdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFabdate.setText("FAB DATE");

        lblEXPDATE.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblEXPDATE.setForeground(new java.awt.Color(0, 102, 102));
        lblEXPDATE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEXPDATE.setText("EXPDATE");

        lblCOMPANY.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCOMPANY.setForeground(new java.awt.Color(0, 102, 102));
        lblCOMPANY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCOMPANY.setText("COMPANY");

        txtFabDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFabDateActionPerformed(evt);
            }
        });

        txtExpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpDateActionPerformed(evt);
            }
        });

        cmbCompany.setBackground(new java.awt.Color(204, 204, 204));
        cmbCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCompanyActionPerformed(evt);
            }
        });

        AddBin.setBackground(new java.awt.Color(153, 153, 153));
        AddBin.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        AddBin.setForeground(new java.awt.Color(0, 102, 102));
        AddBin.setText("ADD");
        AddBin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddBin.setOpaque(false);
        AddBin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBinMouseClicked(evt);
            }
        });
        AddBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBinActionPerformed(evt);
            }
        });

        UpdateBin.setBackground(new java.awt.Color(153, 153, 153));
        UpdateBin.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        UpdateBin.setForeground(new java.awt.Color(0, 102, 102));
        UpdateBin.setText("UPDATE");
        UpdateBin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateBin.setOpaque(false);
        UpdateBin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateBinMouseClicked(evt);
            }
        });
        UpdateBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBinActionPerformed(evt);
            }
        });

        DeleteBin.setBackground(new java.awt.Color(153, 153, 153));
        DeleteBin.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        DeleteBin.setForeground(new java.awt.Color(0, 102, 102));
        DeleteBin.setText("DELETE");
        DeleteBin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteBin.setOpaque(false);
        DeleteBin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBinMouseClicked(evt);
            }
        });
        DeleteBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBinActionPerformed(evt);
            }
        });

        ClearBin.setBackground(new java.awt.Color(153, 153, 153));
        ClearBin.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        ClearBin.setForeground(new java.awt.Color(0, 102, 102));
        ClearBin.setText("CLEAR");
        ClearBin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClearBin.setOpaque(false);
        ClearBin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearBinMouseClicked(evt);
            }
        });
        ClearBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBinActionPerformed(evt);
            }
        });

        tableMedicine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "MEDNAME", "MEDPRICE", "QUANTITY", "FABDATE", "EXBDATE", "COMPANY"
            }
        ));
        tableMedicine.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableMedicine.setRowHeight(25);
        tableMedicine.setSelectionBackground(new java.awt.Color(0, 125, 0));
        tableMedicine.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tableMedicineAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tableMedicine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMedicineMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMedicine);

        jLabel51.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(51, 51, 51));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("MEDICINES LIST");

        btngo.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        btngo.setForeground(new java.awt.Color(0, 102, 102));
        btngo.setText("Next");
        btngo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txtFabdateLayout = new javax.swing.GroupLayout(txtFabdate);
        txtFabdate.setLayout(txtFabdateLayout);
        txtFabdateLayout.setHorizontalGroup(
            txtFabdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtFabdateLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(txtFabdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuantiy)
                    .addComponent(lblBRICE)
                    .addComponent(lblmednane)
                    .addComponent(lblid))
                .addGap(28, 28, 28)
                .addGroup(txtFabdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(txtFabdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addComponent(txtID, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(txtMedName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(txtFabdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtFabdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblEXPDATE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txtFabdateLayout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(lblFabdate)))
                    .addGroup(txtFabdateLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblCOMPANY)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(txtFabdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFabDate, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtFabdateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(txtFabdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtFabdateLayout.createSequentialGroup()
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtFabdateLayout.createSequentialGroup()
                        .addComponent(AddBin)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateBin)
                        .addGap(34, 34, 34)
                        .addComponent(DeleteBin)
                        .addGap(18, 18, 18)
                        .addComponent(ClearBin)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtFabdateLayout.createSequentialGroup()
                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtFabdateLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtFabdateLayout.createSequentialGroup()
                        .addComponent(btngo)
                        .addGap(26, 26, 26))))
        );
        txtFabdateLayout.setVerticalGroup(
            txtFabdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtFabdateLayout.createSequentialGroup()
                .addGroup(txtFabdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtFabdateLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(lblid)
                        .addGap(18, 18, 18)
                        .addComponent(lblmednane, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBRICE, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblQuantiy, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(txtFabdateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(txtFabdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txtFabdateLayout.createSequentialGroup()
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMedName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(txtFabdateLayout.createSequentialGroup()
                                .addGroup(txtFabdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(txtFabdateLayout.createSequentialGroup()
                                        .addGroup(txtFabdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblFabdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFabDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(15, 15, 15)
                                        .addComponent(lblEXPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(txtFabdateLayout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(txtExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(txtFabdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCOMPANY, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(47, 47, 47)
                .addGroup(txtFabdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearBin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btngo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PnlInfoLayout = new javax.swing.GroupLayout(PnlInfo);
        PnlInfo.setLayout(PnlInfoLayout);
        PnlInfoLayout.setHorizontalGroup(
            PnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSelling, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedicines, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFabdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PnlInfoLayout.setVerticalGroup(
            PnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlInfoLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(lblcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMedicines, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblSelling, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(314, Short.MAX_VALUE))
            .addGroup(PnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFabdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblcompanyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcompanyMouseClicked
                new FrmCompany().setVisible(true);
                this.dispose();
    }//GEN-LAST:event_lblcompanyMouseClicked

    private void lblMedicinesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMedicinesMouseClicked
                new frmMediine().setVisible(true);
                this.dispose();
    }//GEN-LAST:event_lblMedicinesMouseClicked

    private void lblSellingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSellingMouseClicked
                new FrmSeling().setVisible(true);
                this.dispose();
    }//GEN-LAST:event_lblSellingMouseClicked

    private void txtMedNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedNameActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void txtFabDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFabDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFabDateActionPerformed

    private void txtExpDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpDateActionPerformed

    private void cmbCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCompanyActionPerformed

    private void AddBinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBinMouseClicked
        ////        try {
            ////            con=DriverManager.getConnection("jdbc:derby://localhost:1527/Pharmadb","aya","123");
            ////            PreparedStatement add=con.prepareStatement("insert into AAGENTTBL values( ?,?,?,?,?,?)");
            ////            add.setInt(1,Integer.valueOf(Aid.getText()));
            ////            add.setString(2,Aname.getText());
            ////            add.setInt(3,Integer.valueOf(Aage.getText()));
            ////            add.setString(4,Aphone.getText());
            ////            add.setString(5,Apass.getText());
            ////
            ////            add.setString(6,GenderCb.getSelectedItem().toString());
            ////            int row=add.executeUpdate();
            ////            JOptionPane.showMessageDialog(this,"Agent Successfully Added");
            ////            con.close();
            ////            selectMed();
            ////        } catch (SQLException e) {
            ////            JOptionPane.showMessageDialog(this, e.getMessage());
            ////            e.printStackTrace();
            ////        }
    }//GEN-LAST:event_AddBinMouseClicked

    private void AddBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBinActionPerformed


    DefaultTableModel model =
    (DefaultTableModel)tableMedicine.getModel();

    model.addRow(new Object[]{
        txtID.getText(),
        txtMedName.getText(),
        txtPrice.getText(),
        txtQuantity.getText(),
        txtFabDate.getText(),
        txtExpDate.getText(),
        cmbCompany.getSelectedItem().toString()
    });


        
        
    }//GEN-LAST:event_AddBinActionPerformed

    private void UpdateBinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateBinMouseClicked
        ////        // التحقق من أن جميع الحقول ممتلئة
        ////        if(Aid.getText().isEmpty() || Aname.getText().isEmpty() || Aage.getText().isEmpty() || Aphone.getText().isEmpty() || Apass.getText().isEmpty()){
            ////            JOptionPane.showMessageDialog(this, "Missing Information");
            ////        }
        ////        else {
            ////            try {
                ////                // 1. فتح الاتصال بقاعدة البيانات
                ////                con = DriverManager.getConnection("jdbc:derby://localhost:1527/Pharmadb", "aya", "123");
                ////
                ////                // 2. جملة SQL الصحيحة (تحتوي على 6 علامات استفهام)
                ////                String UpdateQuery = "UPDATE AYA.AAGENTTBL SET ANAME=?, AAGE=?, APHONE=?, APASS=?, AGENDER=? WHERE AID=?";
                ////
                ////                PreparedStatement pstmt = con.prepareStatement(UpdateQuery);
                ////
                ////                // 3. ربط القيم بالترتيب الصحيح والمطابق لجملة SQL
                ////                pstmt.setString(1, Aname.getText());   // الاسم (ANAME)
                ////                pstmt.setString(2, Aage.getText());    // العمر (AAGE)
                ////                pstmt.setString(3, Aphone.getText());  // الهاتف (APHONE)
                ////                pstmt.setString(4, Apass.getText());   // كلمة السر (APASS)
                ////                pstmt.setString(5, GenderCb.getSelectedItem().toString()); // النوع (AGENDER)
                ////
                ////                // القيمة السادسة (AID) التي تأتي بعد كلمة WHERE لتحديد السطر المطلوب تعديله
                ////                pstmt.setInt(6, Integer.parseInt(Aid.getText()));
                ////
                ////                // 4. تنفيذ التعديل
                ////                int rowsAffected = pstmt.executeUpdate();
                ////
                ////                if (rowsAffected > 0) {
                    ////                    JOptionPane.showMessageDialog(this, "Agent Updated Successfully");
                    ////                    // 5. استدعاء دالة التحديث (تأكد من كتابة اسمها كما هي معرفة عندك)
                    ////                    selectMed();
                    ////                } else {
                    ////                    JOptionPane.showMessageDialog(this, "Agent ID not found!");
                    ////                }
                ////
                ////                // 6. إغلاق الاتصال
                ////                con.close();
                ////
                ////            } catch (SQLException e) {
                ////                // في حال حدوث خطأ في قاعدة البيانات
                ////                e.printStackTrace();
                ////                JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
                ////            } catch (NumberFormatException e) {
                ////                // في حال تم إدخال نص في خانة الـ ID (الذي يجب أن يكون رقماً)
                ////                JOptionPane.showMessageDialog(this, "ID must be a number!");
                ////            } catch (Exception e) {
                ////                // أي أخطاء أخرى
                ////                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
                ////            }
            ////        }
    }//GEN-LAST:event_UpdateBinMouseClicked

    private void UpdateBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBinActionPerformed
     
    DefaultTableModel model =
    (DefaultTableModel)tableMedicine.getModel();

    int row = tableMedicine.getSelectedRow();

    if(row != -1)
    {
        model.setValueAt(txtID.getText(), row, 0);
        model.setValueAt(txtMedName.getText(), row, 1);
        model.setValueAt(txtPrice.getText(), row, 2);
        model.setValueAt(txtQuantity.getText(), row, 3);
        model.setValueAt(txtFabDate.getText(), row, 4);
        model.setValueAt(txtExpDate.getText(), row, 5);
        model.setValueAt(
            cmbCompany.getSelectedItem().toString(),
            row,
            6
        );
    }

    }//GEN-LAST:event_UpdateBinActionPerformed

    private void DeleteBinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBinMouseClicked
        ////        if(Aid.getText().isEmpty()){
            ////            JOptionPane.showMessageDialog(this,"Enter The Agent To Be Deleted");
            ////        }
        ////        else
        ////        try {
            ////            con=DriverManager.getConnection("jdbc:derby://localhost:1527/Pharmadb","aya","123");
            ////            String Id=Aid.getText();
            ////            String Query="Delete from AYA.AAGENTTBL where AID="+Id;
            ////            Statement Add=con.createStatement();
            ////            Add.executeUpdate(Query);
            ////            selectMed();
            ////            JOptionPane.showMessageDialog(this, "Medicine  Delete Successfully " );
            ////        } catch (SQLException e) {
            ////            e.printStackTrace();
            ////        }
    }//GEN-LAST:event_DeleteBinMouseClicked

    private void DeleteBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBinActionPerformed
     
    DefaultTableModel model =
    (DefaultTableModel)tableMedicine.getModel();

    int row = tableMedicine.getSelectedRow();

    if(row != -1)
    {
        model.removeRow(row);
    }


    }//GEN-LAST:event_DeleteBinActionPerformed

    private void ClearBinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearBinMouseClicked

    }//GEN-LAST:event_ClearBinMouseClicked

    private void ClearBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBinActionPerformed
    
       

    txtID.setText("");
    txtMedName.setText("");
    txtPrice.setText("");
    txtQuantity.setText("");
    txtFabDate.setText("");
    txtExpDate.setText("");

    cmbCompany.setSelectedIndex(0);


    }//GEN-LAST:event_ClearBinActionPerformed

    private void tableMedicineAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tableMedicineAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMedicineAncestorAdded

    private void tableMedicineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMedicineMouseClicked
   

    int row = tableMedicine.getSelectedRow();

    txtID.setText(tableMedicine.getValueAt(row,0).toString());
    txtMedName.setText(tableMedicine.getValueAt(row,1).toString());
    txtPrice.setText(tableMedicine.getValueAt(row,2).toString());
    txtQuantity.setText(tableMedicine.getValueAt(row,3).toString());
    txtFabDate.setText(tableMedicine.getValueAt(row,4).toString());
    txtExpDate.setText(tableMedicine.getValueAt(row,5).toString());

    cmbCompany.setSelectedItem(
        tableMedicine.getValueAt(row,6).toString()
    );

        //////        DefaultTableModel mode1=(DefaultTableModel)MedicinTable.getModel();
        //////        int Myindex=MedicinTable.getSelectedRow();
        //////        MedId.setText(mode1.getValueAt(Myindex,0).toString());
        //////        MedName.setText(mode1.getValueAt(Myindex,1).toString());
        //////        MedPrice.setText(mode1.getValueAt(Myindex,2).toString());
        //////        MedQty.setText(mode1.getValueAt(Myindex,3).toString());
    }//GEN-LAST:event_tableMedicineMouseClicked

    private void btngoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngoActionPerformed
        FrmSeling Agents=new FrmSeling();
        Agents.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btngoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMediine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMediine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMediine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMediine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMediine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBin;
    private javax.swing.JButton ClearBin;
    private javax.swing.JButton DeleteBin;
    private javax.swing.JPanel PnlInfo;
    private javax.swing.JButton UpdateBin;
    private javax.swing.JButton btngo;
    private javax.swing.JComboBox<String> cmbCompany;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBRICE;
    private javax.swing.JLabel lblCOMPANY;
    private javax.swing.JLabel lblEXPDATE;
    private javax.swing.JLabel lblFabdate;
    private javax.swing.JLabel lblMedicines;
    private javax.swing.JLabel lblQuantiy;
    private javax.swing.JLabel lblSelling;
    private javax.swing.JLabel lblcompany;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblmednane;
    private javax.swing.JTable tableMedicine;
    private javax.swing.JTextField txtExpDate;
    private javax.swing.JTextField txtFabDate;
    private javax.swing.JPanel txtFabdate;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMedName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
