/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy;

import java.awt.print.PrinterException;
import javax.swing.JOptionPane;

/**
 *
 * @author Shaer
 */
public class FrmSeling extends javax.swing.JFrame {

    /**
     * Creates new form FrmSeling
     */
    public FrmSeling() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlInfo = new javax.swing.JPanel();
        lblMedicine = new javax.swing.JLabel();
        lblAgents = new javax.swing.JLabel();
        lblcompany = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtSeller = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        lblbill = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();
        lblbillid = new javax.swing.JLabel();
        lblmed = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        txtBillId = new javax.swing.JTextField();
        txtMedicine = new javax.swing.JTextField();
        lblLast = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMedicine = new javax.swing.JTable();
        btnAddBill = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblBill = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBill = new javax.swing.JTextArea();
        btnPrint = new javax.swing.JButton();
        lblmed1 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btngo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The process of purchasing medicine");
        setResizable(false);

        PnlInfo.setBackground(new java.awt.Color(0, 102, 102));

        lblMedicine.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        lblMedicine.setForeground(new java.awt.Color(255, 255, 255));
        lblMedicine.setText("MEDICINES");

        lblAgents.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        lblAgents.setForeground(new java.awt.Color(255, 255, 255));
        lblAgents.setText("AGENTS");

        lblcompany.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        lblcompany.setForeground(new java.awt.Color(255, 255, 255));
        lblcompany.setText("COMPANY");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtSeller.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtSeller.setForeground(new java.awt.Color(236, 5, 5));
        txtSeller.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSeller.setText("SELLER");

        txtDate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtDate.setForeground(new java.awt.Color(236, 5, 5));
        txtDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDate.setText("DATE");

        lblbill.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        lblbill.setForeground(new java.awt.Color(51, 51, 51));
        lblbill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbill.setText("BILLING");

        lblQty.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblQty.setForeground(new java.awt.Color(0, 102, 102));
        lblQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQty.setText("QTY");

        lblbillid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblbillid.setForeground(new java.awt.Color(0, 102, 102));
        lblbillid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbillid.setText("BILLID");

        lblmed.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblmed.setForeground(new java.awt.Color(0, 102, 102));
        lblmed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmed.setText("MEDICINE");

        lblLast.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        lblLast.setForeground(new java.awt.Color(51, 51, 51));
        lblLast.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLast.setText("MEDICINES LIST");

        tableMedicine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "MEDNAME", "MEDPRICE", "QUANTITY", "FABDATE", "EXBDATE", "COMPANY"
            }
        ));
        tableMedicine.setRowHeight(25);
        tableMedicine.setSelectionBackground(new java.awt.Color(0, 125, 0));
        tableMedicine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMedicineMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMedicine);

        btnAddBill.setBackground(new java.awt.Color(153, 153, 153));
        btnAddBill.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        btnAddBill.setForeground(new java.awt.Color(0, 102, 102));
        btnAddBill.setText("ADD TO BILL");
        btnAddBill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddBillMouseClicked(evt);
            }
        });
        btnAddBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBillActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(153, 153, 153));
        btnClear.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 102, 102));
        btnClear.setText("CLEAR");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblBill.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        lblBill.setForeground(new java.awt.Color(51, 51, 51));
        lblBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBill.setText("BILL");

        txtBill.setColumns(20);
        txtBill.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtBill.setForeground(new java.awt.Color(0, 102, 102));
        txtBill.setRows(5);
        txtBill.setText("             **********************Pharma Center********************");
        jScrollPane2.setViewportView(txtBill);

        btnPrint.setBackground(new java.awt.Color(153, 153, 153));
        btnPrint.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(51, 204, 0));
        btnPrint.setText("PRINT");
        btnPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrintMouseClicked(evt);
            }
        });
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        lblmed1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblmed1.setForeground(new java.awt.Color(0, 102, 102));
        lblmed1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmed1.setText("PRICE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(296, 296, 296))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblbillid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtSeller)
                                .addGap(30, 30, 30)
                                .addComponent(lblbill, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(txtDate))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txtBillId, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblmed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblmed1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(lblQty)))
                        .addGap(18, 18, 18)
                        .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(304, 304, 304)
                                .addComponent(lblBill, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(btnAddBill)
                                .addGap(162, 162, 162)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLast, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSeller, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbill, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmed, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQty, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBillId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbillid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmed1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(lblLast, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddBill, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBill, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        btngo.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        btngo.setForeground(new java.awt.Color(0, 102, 102));
        btngo.setText("Exit");
        btngo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlInfoLayout = new javax.swing.GroupLayout(PnlInfo);
        PnlInfo.setLayout(PnlInfoLayout);
        PnlInfoLayout.setHorizontalGroup(
            PnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlInfoLayout.createSequentialGroup()
                .addGroup(PnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlInfoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(PnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlInfoLayout.createSequentialGroup()
                                .addComponent(lblAgents, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlInfoLayout.createSequentialGroup()
                                .addComponent(btngo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PnlInfoLayout.setVerticalGroup(
            PnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PnlInfoLayout.createSequentialGroup()
                        .addComponent(lblMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAgents, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(356, 356, 356)
                        .addComponent(btngo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableMedicineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMedicineMouseClicked


    int row = tableMedicine.getSelectedRow();

    txtMedicine.setText(
        tableMedicine.getValueAt(row,1).toString()
    );

    txtPrice.setText(
        tableMedicine.getValueAt(row,2).toString()
    );




////        DefaultTableModel mode1=(DefaultTableModel)MedicinTabl.getModel();
////        int Myindex=MedicinTabl.getSelectedRow();
////        MedText.setText(mode1.getValueAt(Myindex,1).toString());
////        Medid=Integer.valueOf(mode1.getValueAt(Myindex,0).toString());
////        //MedName.setText(mode1.getValueAt(Myindex,1).toString());
////        // MedPrice.setText(mode1.getValueAt(Myindex,2).toString());
////        // MedQty.setText(mode1.getValueAt(Myindex,3).toString());
////        price=Integer.valueOf(mode1.getValueAt(Myindex,2).toString());
    }//GEN-LAST:event_tableMedicineMouseClicked

    private void btnAddBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddBillMouseClicked
//        CompId.setText("");
//        MedText.setText("");
//        //Compadd.setText("");
//        //CompPhone.setText("");
//        //Compexp.setText("");
    }//GEN-LAST:event_btnAddBillMouseClicked

    private void btnAddBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBillActionPerformed
     

    double price =
    Double.parseDouble(txtPrice.getText());

    int qty =
    Integer.parseInt(txtQty.getText());

    double total = price * qty;

    txtBill.setText(

    "=================================\n" +
    "          PHARMA CENTER\n" +
    "=================================\n\n" +

    "Seller : " + txtSeller.getText() + "\n" +

    "Date : " + txtDate.getText() + "\n" +

    "Bill ID : " + txtBillId.getText() + "\n\n" +

    "Medicine : " + txtMedicine.getText() + "\n" +

    "Price : " + txtPrice.getText() + "\n" +

    "Quantity : " + txtQty.getText() + "\n\n" +

    "Total : " + total + " JD\n\n" +

    "=================================\n" +
    "      Thank You For Visiting Us\n" +
    "================================="
    );

    }//GEN-LAST:event_btnAddBillActionPerformed

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
      

    txtSeller.setText("");
    txtDate.setText("");
    txtBillId.setText("");
    txtMedicine.setText("");
    txtPrice.setText("");
    txtQty.setText("");

    txtBill.setText("");

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseClicked
        /* // 1. التحقق من أن جميع الحقول ممتلئة (باستخدام أسماء متغيرات الشركات)
        if(CompId.getText().isEmpty() || Compname.getText().isEmpty() || Compadd.getText().isEmpty() || Compexp.getText().isEmpty() || CompPhone.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Missing Information");
        }
        else {
            try {
                // 1. فتح الاتصال بقاعدة البيانات
                con = DriverManager.getConnection("jdbc:derby://localhost:1527/Pharmadb", "aya", "123");

                // 2. جملة SQL الصحيحة (بدون فاصلة زائدة قبل WHERE وبـ 5 علامات استفهام)
                String UpdateQuery = "UPDATE AYA.COMPANYTBL SET COMPNAME=?, COMPAD=?, COMPEXP=?, COMPPHONE=? WHERE COMPID=?";

                PreparedStatement pstmt = con.prepareStatement(UpdateQuery);

                // 3. ربط القيم بالترتيب الصحيح والمطابق لعلامات الاستفهام (?)
                pstmt.setString(1, Compname.getText());  // الاسم (COMPNAME)
                pstmt.setString(2, Compadd.getText());   // العنوان (COMPAD)
                pstmt.setString(3, Compexp.getText());   // الخبرة (COMPEXP)
                pstmt.setString(4, CompPhone.getText()); // الهاتف (COMPPHONE)

                // القيمة الخامسة هي الـ ID الذي نستخدمه في البحث (WHERE AID=?)
                pstmt.setInt(5, Integer.parseInt(CompId.getText()));

                // 4. تنفيذ التعديل
                int rowsAffected = pstmt.executeUpdate();

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Company Updated Successfully");
                    // 5. استدعاء دالة تحديث الجدول
                    selectMed();
                } else {
                    JOptionPane.showMessageDialog(this, "Company ID not found!");
                }

                // 6. إغلاق الاتصال
                con.close();

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ID must be a number!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }*/
        try {
            txtBill.print();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPrintMouseClicked

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
       

    try {

        txtBill.print();

    } catch (PrinterException ex) {

        JOptionPane.showMessageDialog(
            this,
            "Print Error"
        );

    }

    }//GEN-LAST:event_btnPrintActionPerformed

    private void btngoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngoActionPerformed
        SPLASH Agents=new SPLASH();
        Agents.setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_btngoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSeling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSeling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSeling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSeling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSeling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlInfo;
    private javax.swing.JButton btnAddBill;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btngo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAgents;
    private javax.swing.JLabel lblBill;
    private javax.swing.JLabel lblLast;
    private javax.swing.JLabel lblMedicine;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblbill;
    private javax.swing.JLabel lblbillid;
    private javax.swing.JLabel lblcompany;
    private javax.swing.JLabel lblmed;
    private javax.swing.JLabel lblmed1;
    private javax.swing.JTable tableMedicine;
    private javax.swing.JTextArea txtBill;
    private javax.swing.JTextField txtBillId;
    private javax.swing.JLabel txtDate;
    private javax.swing.JTextField txtMedicine;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQty;
    private javax.swing.JLabel txtSeller;
    // End of variables declaration//GEN-END:variables
}
