/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Shaer
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlInfo = new javax.swing.JPanel();
        lblpharma = new javax.swing.JLabel();
        lblsystem = new javax.swing.JLabel();
        lblcode = new javax.swing.JLabel();
        Pnllogin = new javax.swing.JPanel();
        lbllogin = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        btnlogin = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        lblcodespace = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pharmacy Center Login");
        setResizable(false);

        PnlInfo.setBackground(new java.awt.Color(0, 102, 102));

        lblpharma.setFont(new java.awt.Font("Script MT Bold", 1, 22)); // NOI18N
        lblpharma.setForeground(new java.awt.Color(255, 255, 255));
        lblpharma.setText("PharmaCenter");

        lblsystem.setFont(new java.awt.Font("Script MT Bold", 1, 22)); // NOI18N
        lblsystem.setForeground(new java.awt.Color(255, 255, 255));
        lblsystem.setText("Centralized System");

        lblcode.setFont(new java.awt.Font("Script MT Bold", 1, 22)); // NOI18N
        lblcode.setForeground(new java.awt.Color(255, 255, 255));
        lblcode.setText("CodeSpace");

        Pnllogin.setBackground(new java.awt.Color(204, 204, 204));

        lbllogin.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        lbllogin.setForeground(new java.awt.Color(51, 51, 51));
        lbllogin.setText("LOGIN");

        lblname.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        lblname.setForeground(new java.awt.Color(0, 102, 102));
        lblname.setText("Name");

        lblpassword.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        lblpassword.setForeground(new java.awt.Color(0, 102, 102));
        lblpassword.setText("Password");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        btnlogin.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(0, 102, 102));
        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        btnclear.setForeground(new java.awt.Color(0, 102, 102));
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        lblcodespace.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        lblcodespace.setForeground(new java.awt.Color(0, 102, 102));
        lblcodespace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcodespace.setText("Codespace");

        javax.swing.GroupLayout PnlloginLayout = new javax.swing.GroupLayout(Pnllogin);
        Pnllogin.setLayout(PnlloginLayout);
        PnlloginLayout.setHorizontalGroup(
            PnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlloginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlloginLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnclear)
                        .addGap(18, 18, 18)
                        .addComponent(btnlogin))
                    .addGroup(PnlloginLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(PnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PnlloginLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(lbllogin, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlloginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblcodespace, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PnlloginLayout.setVerticalGroup(
            PnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlloginLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lbllogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(PnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(PnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(txtpassword))
                .addGap(52, 52, 52)
                .addGroup(PnlloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlogin)
                    .addComponent(btnclear))
                .addGap(60, 60, 60)
                .addComponent(lblcodespace)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PnlInfoLayout = new javax.swing.GroupLayout(PnlInfo);
        PnlInfo.setLayout(PnlInfoLayout);
        PnlInfoLayout.setHorizontalGroup(
            PnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlInfoLayout.createSequentialGroup()
                        .addComponent(lblpharma, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlInfoLayout.createSequentialGroup()
                        .addComponent(lblsystem)
                        .addGap(7, 7, 7))
                    .addGroup(PnlInfoLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblcode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(Pnllogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PnlInfoLayout.setVerticalGroup(
            PnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlInfoLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(lblpharma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblsystem, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblcode, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Pnllogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed

//        FrmCompany Company=new FrmCompany();
//        Company.setVisible(true);
//        this.setVisible(false);
           if (nameValidation(txtname)&&passwordValidation(txtpassword) ) {
            String name = txtname.getText().trim();
            String password = txtpassword.getText().trim();
      
       
//        String username=txtname.getText().trim();
//        String password=txtpassword.getText().trim();
        if(name.equals("admin") && password.equals("12345")){
            SPLASH main=new SPLASH();
            main.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this, "Invalid username or password ");
        }
       }  
      
//    lblResulte.setText("your Name:\n"+txtname.getText());
//    lblResulte.setText(lblResulte.getText()+"\n your Password: "+txtpassowrd.getText());
//   
    }//GEN-LAST:event_btnloginActionPerformed
  public boolean nameValidation(JTextField txt){
        String text = txt.getText().trim();
        if (text.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "field is Required");
            txt.requestFocus();
            txt.setBorder(BorderFactory.createLineBorder(Color.red));
           return false; 
        }
          txt.setBorder(BorderFactory.createLineBorder(Color.gray));
        return true;
    }
    
    
    public boolean passwordValidation(JTextField txt){
        String text = txt.getText().trim();
        if (text.isEmpty()) {
            JOptionPane.showMessageDialog(this, "field is Required");
            txt.requestFocus();
            txt.setBorder(BorderFactory.createLineBorder(Color.red));
           return false; 
        }
          txt.setBorder(BorderFactory.createLineBorder(Color.gray));
        return true;
    }

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
       txtname.setText("");
       txtpassword.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    
    
    
    
    
    
    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlInfo;
    private javax.swing.JPanel Pnllogin;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel lblcode;
    private javax.swing.JLabel lblcodespace;
    private javax.swing.JLabel lbllogin;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblpharma;
    private javax.swing.JLabel lblsystem;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
